
class Config:
    #Github keys
    GITHUB_APP_ID = "GITHUB_APP_ID"
    GITHUB_APP_PRIVATE_KEY = "GITHUB_APP_PRIVATE_KEY"
    GITHUB_REPOSITORY = "GITHUB_REPOSITORY"

    #Gemini keys
    GEMINI_API_KEY = ""